CREATE DATABASE IF NOT EXISTS ventaconsolas;

USE ventaconsolas;

CREATE TABLE porempresa(
  pais_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  dominio CHAR(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE consolasmasvendidas(
  plataforma_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  unidades VARCHAR(50) NOT NULL,
  generacion CHAR NOT NULL,
  cantidad INTEGER UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tipos(
  tipo_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sobremesa VARCHAR(50) NOT NULL,
  portatil VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE consolaXtipo(
  consola_x_tipo_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tipo_id INTEGER UNSIGNED,
  plataforma_id INTEGER UNSIGNED 
  fecha DATETIME NOT NULL,
  FOREIGN KEY(tipo_id)
    REFERENCES tipos(tipo_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

a